---
title: "Loop to Create Playlists"
author: "Mike Kaminski"
date: "2023-10-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```


```{r libraries, include=FALSE}
library(httr)
library(lubridate)
library(spotifyr)
library(tidyverse)
library(tinyspotifyr)
```

#loads data
```{r message = FALSE}
loop_df <- read_csv("PlaylistCreator/app_df.csv") %>% select(-1)%>% arrange(venue,show_date) %>% na.omit()
# app_df <- read_csv("PlaylistCreator/app_df.csv") %>% select(-1) %>% filter(venue %in% 'The Salt Shed' & show_date < '2023-10-23')
# loop_df <- read_csv("PlaylistCreator/app_df.csv") %>% select(-1) %>% filter(venue %in% 'The Salt Shed' & show_date > '2023-10-03')
```


## Sets up the environment
```{r}
Sys.setenv(SPOTIFY_CLIENT_ID = '9b5eb134223f4cb5a0c4834fa5742d9e')
Sys.setenv(SPOTIFY_CLIENT_SECRET = 'b742be8a81ba469794bd3146dac1d080')

access_token <- get_spotify_access_token()
```

# Creates the initial playlists
```{r}
unique_venue <- unique(loop_df$venue)
date_range1 <- Sys.Date()
date_range2 <- Sys.Date() + 30

# loop_df %>% filter(venue %in% 'Martyrs’')
# unique_venue <- 'The Riviera Theatre'

#For loop that creates new playlists if necessary.  It will be used initially and then afterwards if new venues are added.  Right now there are only 12ish venues
for (uv in unique_venue) {
  # defines the playlist name
  playlist_name <- paste('Next30:',uv, sep = " ")  # the name of the venue

  playlist <- create_playlist('mikekaminski25', playlist_name, public = TRUE,
                        description = paste('Top songs on Spotify for bands playing at',
                                            uv,
                                            'between',
                                            format(as.Date(date_range1, format = "%d/%m/%Y"), "%b %d"),
                                            'and',
                                            format(as.Date(date_range2, format = "%d/%m/%Y"), "%b %d"), sep = ' '))
  
  playlist_uri <- loop_df %>% filter(venue %in% uv) %>% select(track_uri) %>% na.omit() %>% unlist()
  playlist_id <- sub("spotify:playlist:", "", playlist$uri)
    
  batch_size <- 100
  for (i in seq(1, length(playlist_uri), by = batch_size)) {
    batch <- playlist_uri[i:min(i + batch_size - 1, length(playlist_uri))]
    add_tracks_to_playlist(playlist_id, batch)
    }
  }
```

# Updates the playlists
```{r}
# gets all the playlists
my_playlists <- tinyspotifyr::get_my_playlists(limit = 50) # gets the playlist names

old_counts <- my_playlists %>% select(name, tracks.total) %>% filter(grepl('Next30',name))

# sets venue and date variables
unique_venue <- unique(loop_df$venue)
# uv <- unique_venue
date_range1 <- Sys.Date()
date_range2 <- Sys.Date() + 30

#####FOR LOOP
for (uv in unique_venue) {
  
  # defines the playlist name
  playlist_name <- paste('Next30:',uv, sep = " ")  # the name of the venue
  
  # Logical to get the playlist that matches
  playlist_logical <- (my_playlists$name == playlist_name)
  
  # Other variables, eventually landing on the playlist_id
  ind <- which(playlist_logical)
  dr <- my_playlists[ind, ]
  playlist_id <- sub("spotify:playlist:", "", dr$uri)

  # Number of track on the playlist
  old_playlist_tracks <- old_counts[grep(uv, old_counts$name), c("tracks.total")]
  batch_size <- 100
  
  # Calculate the number of iterations needed
  num_iterations <- ceiling(old_playlist_tracks / batch_size)
  
  # Initialize an empty vector to store all the playlist tracks
  old_playlist_track_ids <- character(0)
  
  # Loop through the iterations
  for (i in 1:num_iterations) {
    songs <- get_playlist_tracks(playlist_id, offset = (i*100-100)) 
    track_ids <- paste("spotify:track:", songs$track.id, sep="") %>%unlist()
    
    # Extract the track names from the current batch and add them to the 'all_tracks' vector
    old_playlist_track_ids <- c(old_playlist_track_ids, track_ids)
    # old_playlist_track_ids <- unique(old_playlist_track_ids)
  }

  # gets updated track list from the loff_df from before
  new_playlist_track_ids <- loop_df %>% filter(venue %in% uv) %>% select(track_uri) %>% unlist()
  
  # identifies the songs that are different
  old_songs <- setdiff(old_playlist_track_ids,new_playlist_track_ids)
  new_songs <- setdiff(new_playlist_track_ids,old_playlist_track_ids)
    
  # Adds new songs
  if (length(new_songs) == 0) {
    # Skip the code if new_songs is empty
    cat("No new songs to add.\n")
    } else {
    
    # Calculate the batch size
    batch_size <- 100
    
    # Add items to the playlist in batches
    for (i in seq(1, length(new_songs), by = batch_size)) {
      batch <- new_songs[i:min(i + batch_size - 1, length(new_songs))]
      add_items_to_playlist(playlist_id, batch)
    }
  }

  #removes the old songs
  remove_tracks_from_playlist(
    playlist_id,
    old_songs
  )
  
  # updates the playlist details
  change_playlist_details(playlist_id,
                        description = paste('Top songs on Spotify for bands playing at',
                        uv,
                        'between',
                        format(as.Date(date_range1, format = "%d/%m/%Y"), "%b %d"),
                        '-',
                        format(as.Date(date_range2, format = "%d/%m/%Y"), "%b %d"), sep = ' '))
}

my_playlists <- tinyspotifyr::get_my_playlists(limit = 50) # gets the playlist names

new_counts <- my_playlists %>% select(name, tracks.total) %>% filter(grepl('Next30',name))

# left_join(old_counts, new_counts, by = 'name', keep = TRUE)

```


```{r}
# gets all the playlists
my_playlists <- tinyspotifyr::get_my_playlists(limit = 50) # gets the playlist names

old_counts <- my_playlists %>% select(name, tracks.total) %>% filter(grepl('Next30',name))

# sets venue and date variables
unique_venue <- unique(loop_df$venue)


for (uv in unique_venue) {
  
  # defines the playlist name
  playlist_name <- paste('Next30:',uv, sep = " ")  # the name of the venue
  
  # Logical to get the playlist that matches
  playlist_logical <- (my_playlists$name == playlist_name)
  
  # Other variables, eventually landing on the playlist_id
  ind <- which(playlist_logical)
  dr <- my_playlists[ind, ]
  playlist_id <- sub("spotify:playlist:", "", dr$uri)
  
    # Number of track on the playlist
  old_playlist_tracks <- old_counts[grep(uv, old_counts$name), c("tracks.total")]
  batch_size <- 100
  
  # Calculate the number of iterations needed
  num_iterations <- ceiling(old_playlist_tracks / batch_size)
  
  # Initialize an empty vector to store all the playlist tracks
  old_playlist_track_ids <- character(0)
  
  # Loop through the iterations
  for (i in 1:num_iterations) {
    songs <- get_playlist_tracks(playlist_id, offset = (i*100-100)) 
    track_ids <- paste("spotify:track:", songs$track.id, sep="") %>%unlist()
    
    # Extract the track names from the current batch and add them to the 'all_tracks' vector
    old_playlist_track_ids <- c(old_playlist_track_ids, track_ids)

  }
  
 # removes the old songs
  remove_tracks_from_playlist(
    playlist_id,
    where(count(old_playlist_track_ids$track.uri) > 1))
  )
  
# Identify duplicate track URIs
duplicate_indices <- duplicated(old_playlist_track_ids)

# Remove duplicates from the old_playlist_track_ids data frame
old_playlist_track_ids <- old_playlist_track_ids[!duplicate_indices, ]

# Remove duplicate tracks from the playlist
remove_tracks_from_playlist(playlist_id, track_uris = old_playlist_track_ids$track.uri)

```


```{r}
my_playlists <- tinyspotifyr::get_my_playlists(limit = 50) # gets the playlist names

library(tidymodels)


test <- get_playlist_tracks('3Co2Gz21d7gnRVknnHA9Hs')
glimpse(test$track.artists)


test$track.artists[[1]]$name

sapply(test$track.artists, function(x) x$name)

loop_df %>% filter(venue %in% 'The Salt Shed') %>% distinct(artist,show_date) %>% arrange(show_date)
```


```{r}
devtools::install_github("rstudio/addinexamples", type = "source")
```











